### ISSUE TITLE
能否加入申请人的专精以及种族信息显示？

### ISSUE THREAD

**Issue by Enocyl** [brooklynb7/MeetingStone_Happy#19]
以下是ChatGPT的回答：

**

> 在《魔兽世界》的Lua API中，你可以使用UnitRace(unit)和GetSpecializationInfoForClassID(classID)函数来获取一个单位的种族和专精。然而，这些函数只能用于你当前可以交互的单位，例如你的目标或者你的队伍成员。你不能用这些函数来获取任意一个玩家的种族和专精。
> 
>   -- 获取玩家的种族和专精
>   local unit = "player" -- 或者其他单位，如"target"
>   local race = UnitRace(unit)
>   local classID = select(3, UnitClass(unit))
>   local specID = GetSpecializationInfoForClassID(classID)
>   local specName = select(2, GetSpecializationInfoByID(specID))
> 
>   -- 添加到提示框
>   tooltip:AddLine(format("种族: %s", race))
>   tooltip:AddLine(format("专精: %s", specName))

**

集合石的申请人似乎不太能满足上面的可交互要求，不知道能否实现？

**Comment by brooklynb7** [comment]
加入了显示专精
