### ISSUE TITLE
刷新时一直卡在搜寻中

### ISSUE THREAD

**Issue by rere43** [brooklynb7/MeetingStone_Happy#32]
我的情况是只有用10.2.0 20231118v2才能搜到队伍, 新版本04年5月后的几个版本试过都是点刷新时一直在搜寻中 ,

**Comment by brooklynb7** [comment]
最近刚更新了前夕11.0，看看还有没有这个问题

**Comment by wweggplant** [comment]
使用730这个版本还是搜不到 @brooklynb7

**Comment by brooklynb7** [comment]
> 使用730这个版本还是搜不到 @brooklynb7

看一下有没有之前写过的装等啥的留在了过滤条件里。
或者截图看一下，是什么样子的搜索不到

**Comment by brooklynb7** [comment]
11.0.7更新，如有问题在reopen
